export enum WizzardState {
  LANDING_PAGE = 'LANDING_PAGE',
  NEW_CHAT = 'NEW_CHAT',
  EXISTING_CHAT = 'EXISTING_CHAT',
  SHARED_CONVERSATION = 'SHARED_CONVERSATION',
  CHAT_FEATURES = 'CHAT_FEATURES'

}
